### ISSUE TITLE
zorgs not found

### ISSUE THREAD

**Issue by DirtyF** [vvo/zorgs#1]
Nice project. Didn't manage to obtain the same output as mentioned in the README though:

```
$ npm install -g zorgs
npm WARN apollo-link-http@1.3.2 requires a peer of graphql@^0.11.0 but none is installed. You must install peer dependencies yourself.

+ zorgs@1.0.0
updated 1 package in 2.913s

$ zorgs
zsh: command not found: zorgs
```

Is there other undocumented steps to install properly?

**Comment by vvo** [comment]
Thanks @DirtyF also see https://github.com/vvo/zorgs/issues/2, let me know if everything works

**Comment by DirtyF** [comment]
I have different outputs depending on the org:

On a org I'm not owner of:

```
Current organization: https://github.com/jekyll
GitHub rate limit: 4 999/5 000

⠦ Computing repositoriesError: Table must have a consistent number of cells.
    at exports.default.rows (/usr/local/lib/node_modules/zorgs-cli/node_modules/table/dist/validateTableData.js:40:13)
    at exports.default (/usr/local/lib/node_modules/zorgs-cli/node_modules/table/dist/table.js:116:35)
    at formatRepositories (/usr/local/lib/node_modules/zorgs-cli/src/formatters/formatRepositories.js:23:10)
    at run (/usr/local/lib/node_modules/zorgs-cli/src/index.js:65:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

👍 Works fine for an org I created and I can manage.

**Comment by vvo** [comment]
I think I know why, it's when there are no private or public repositories created for year + 1 when year -1 had some, thus the number of cells is not the same.

I'll have a look but if you want to go ahead :D

**Comment by DirtyF** [comment]
> do you have the org name?

```
Current organization: https://github.com/jekyll
```

**Comment by vvo** [comment]
Could not reproduce on the current version: 

```sh
┌────────────────────────────────┐
│                                │
│            🦑  zorgs            │
│   GitHub organizations stats   │
│                                │
└────────────────────────────────┘

Current organization: https://github.com/jekyll
GitHub rate limit: 5,000/5,000

Repositories created per year:
╔══════════════╤══════╤══════╤══════╤══════╤══════╤══════╤══════╤══════════╗
║ Year         │ 2008 │ 2013 │ 2014 │ 2015 │ 2016 │ 2017 │ 2018 │ All-time ║
╟──────────────┼──────┼──────┼──────┼──────┼──────┼──────┼──────┼──────────╢
║ Repositories │ 1    │ 9    │ 25   │ 5    │ 4    │ 2    │ 1    │ 47       ║
╚══════════════╧══════╧══════╧══════╧══════╧══════╧══════╧══════╧══════════╝

Commits pushed per year:
╔═════════╤══════╤══════╤══════╤══════╤══════╤═══════╤═══════╤═══════╤═══════╤═══════╤══════╤══════════╗
║ Year    │ 2008 │ 2009 │ 2010 │ 2011 │ 2012 │ 2013  │ 2014  │ 2015  │ 2016  │ 2017  │ 2018 │ All-time ║
╟─────────┼──────┼──────┼──────┼──────┼──────┼───────┼───────┼───────┼───────┼───────┼──────┼──────────╢
║ Commits │ 184  │ 232  │ 178  │ 141  │ 131  │ 2,640 │ 3,363 │ 2,114 │ 4,140 │ 2,674 │ 234  │ 16,031   ║
╚═════════╧══════╧══════╧══════╧══════╧══════╧═══════╧═══════╧═══════╧═══════╧═══════╧══════╧══════════╝


GitHub rate limit: 4,987/5,000
```

**Comment by vvo** [comment]
If you can reproduce it, open a new issue, thanks!
